server:
  port: 9002

spring:
  application:
    name: good-service

eureka:
  instance:
    hostname: goods-server-two
  client:
    serviceUrl:
          defaultZone: http://eureka-server-one:8761/eureka/,http://eureka-server-two:8762/eureka/,http://eureka-server-three:8763/eureka/


